apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  config.yaml: |-
    user:
      db:
        host: 'user-db'
        port: ':3306'
        user: 'root'
        password: ''
        name: 'users'
      server:
        name: 'user'
        host: 'user-server'
        port: ':50051'
      http:
        port: ':8051'
    post:
      db:
        host: 'post-db'
        port: ':3306'
        user: 'root'
        password: ''
        name: 'posts'
      server:
        name: 'post'
        host: 'post-server'
        port: ':50052'
      http:
        port: ':8052'
    comment:
      db:
        host: 'comment-db'
        port: ':3306'
        user: 'root'
        password: ''
        name: 'comments'
      server:
        name: 'comment'
        host: 'comment-server'
        port: ':50053'
      http:
        port: ':8053'
    auth:
      server:
        name: 'auth'
        host: 'auth-server'
        port: ':50054'
      http:
        port: ':8054'
    jwt:
      secret: 'secret'
      expires: 36000
