user:
  db:
    host: 'localhost'
    port: ':3306'
    user: 'root'
    password: ''
    name: 'users'
  server:
    name: 'user'
    host: 'localhost'
    port: ':50051'
  http:
    port: ':8051'
post:
  db:
    host: 'localhost'
    port: ':3306'
    user: 'root'
    password: ''
    name: 'posts'
  server:
    name: 'post'
    host: 'localhost'
    port: ':50052'
  http:
    port: ':8052'
comment:
  db:
    host: 'localhost'
    port: ':3306'
    user: 'root'
    password: ''
    name: 'comments'
  server:
    name: 'comment'
    host: 'localhost'
    port: ':50053'
  http:
    port: ':8053'
auth:
  server:
    name: 'auth'
    host: 'localhost'
    port: ':50054'
  http:
    port: ':8054'
jwt:
  secret: 'secret'
  expires: 36000